title: Don Fils
email: filsdonbrice@gmail.com
description: "Don Fils is a Communication Designer based in Miami. His work spans the disciplines of Graphic Design, Photography, and Art Direction."
keywords:
  - "Communication Designer"
  - "Graphic Design"
  - "Photography"
  - "Art Direction"

baseurl: "/don-fils"
url: "https://zacharyrnewton.github.io"




# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
